### ISSUE TITLE
YML files that are an array are broken

### ISSUE THREAD

**Issue by ericroberts** [ericroberts/tint#1]
It will render the page but the names of the inputs will be wrong.

Example, data looks like this:

``` yaml
- name: "stuff"
  something: "other stuff"
- name: "stuff 2"
  something: "other stuff 2"
```

sets all the names of the root level inputs to `[]`, when it should be `data[][name]` and `data[][something]`.
